language: bash
notifications:
  email: false
git:
  submodules: false
sudo: true
install: true
before_script:
  - sudo mkdir /home/${USER}
  - sudo chmod 777 /home/${USER}
script:
  - whoami
  - make install
  - make test
