language: bash
notifications:
  email: false
git:
  submodules: false
install: true
before_script:
  - mkdir $HOME/testhome
  - export HOME=$HOME/testhome
script:
  - make initialize
  - make install
  - make test
