language: bash
notifications:
  email: false
git:
  submodules: false
env:
  global:
    - TEST_HOME=$HOME/testhome
install: true
before_script:
  - mkdir $TEST_HOME
  - export HOME=$TEST_HOME
script:
  - make install
  - make test
